name: Deploy SvelteKit ðŸš€

on:
  push:
    branches: [main]
    # Sustainability: Don't trigger build for updated README
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Pull repository into the current pipeline
      - name: Pull repository
        uses: actions/checkout@v3

      # Setup NodeJS LTS
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build the build/-directory, ci = clean install
      - name: "Install and build via npm ðŸ”§" 
        run: |
          npm ci
          npm run build

      - name: "Debug: Show generated files"
        run: |
          ls -ls

      # TODO: Disabled by now, this lead to a 404/500 not found error for /sverdle ðŸ¤”
      # Create an optimized node_modules folder
      # https://kit.svelte.dev/docs/adapter-node recommends "--omit dev"
      # - name: "Create node_modules for server (optimized)"
      #   run: |
      #     rm -rf node_modules/
      #     npm ci --omit dev

      # - name: "Debug: Show generated files"
      #   run: |
      #     ls -ls

      # rsync (via SSH key auth)
      # https://github.com/Burnett01/rsync-deployments
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          # be careful with --delete option, use --dry-run to check connection
          switches: -avvvzr --delete --exclude="/.git/" --exclude="/.github/"
          # local path, defaults to GITHUB_WORKSPACE and is relative to it
          path: /
          # remote_path, something like /html/sveltekit-p-n238roi4/ 
          remote_path: /html/sveltekit-demo-u7qzj/
          remote_host: ssh.fabbenstedt.project.host
          remote_user: ssh-f2fuxn@p-ni13ir
          # The private key, public key part must be added to Mittwald project/user
          remote_key: ${{ secrets.SSH_KEY }}

      # Restart NodeJS app after file change via SSH command
      # https://github.com/appleboy/ssh-action
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@v0.1.10
        # if you need variables inside the script commands
        env:
          SSH_PATH: /html/sveltekit-demo-u7qzj/
        with:
          host: ssh.fabbenstedt.project.host
          username: ssh-f2fuxn@p-ni13ir
          key: ${{ secrets.SSH_KEY }}
          envs: SSH_PATH
          # TODO: cd in to $SSH_PATH needed in future?
          script: |
            mittnitectl job restart node
